### ISSUE TITLE
能否说手具体该怎么用啊

### ISSUE THREAD

**Issue by zwb124** [baranwang/homebridge-plugin-aqara#10]
我知道配置里的appid什么的是开发者平台上的，我注册了开发者平台，然后怎么操作呢？感谢

**Comment by baranwang** [comment]
1. 配置一下 aqara 开发者平台的应用信息
2. 输入你绑定设备的 aqara 账号，获取验证码
3. 点击获取 Token，看到界面显示你的 Access Token 就好了

**Comment by zwb124** [comment]
> 1. 配置一下 aqara 开发者平台的应用信息
> 2. 输入你绑定设备的 aqara 账号，获取验证码
> 3. 点击获取 Token，看到界面显示你的 Access Token 就好了

我获取到access token了，但是重启hb后没有任何设备显示，有可能是啥问题呢？

**Comment by zwb124** [comment]
我的晾衣杆是lumi.airer.acn001

**Comment by baranwang** [comment]
哦 目前只实现了 lumi.airer.acn02 我不确定这两款的差异性，你要不邀请一下 `me@baran.wang` 这个账号，我看一下

**Comment by zwb124** [comment]
> 哦 目前只实现了 lumi.airer.acn02 我不确定这两款的差异性，你要不邀请一下 `me@baran.wang` 这个账号，我看一下

邀请你了，方便加个微信吗？v：endiMTI0（base64）
